WINDOW_X, WINDOW_Y = 800, 600
FRAME = 24
MAX_SHAPE_PCT = 2.0
MIN_SHAPE_PCT = .4
STANDARD_HEALTH = 100
SLEEP_INTERVAL = 1 / FRAME
UP, DOWN, RIGHT, LEFT, STOP = "up", "down", "right", "left", "stop"
BATTLE_UNIT_BASE_SPEED = 50 / FRAME      # 50 pixel per second
MISSILE_BASE_SPEED = 200 / FRAME    # 200 pixel per second
ENFORCER = "ENFORCER"
SNIPER = "SNIPER"

AI_DECISION_MOVE = "AI_DECISION_MOVE"
AI_DECISION_ATTACK = "AI_DECISION_ATTACK"


ENABLE_CANVAS_MOVING = False
